# -*- coding: utf-8 -*-
"""hw6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjuNpR9aBCrQQzU0oyM4CorwVTRmKcox
"""


# prompt: # Homework 6
# 1. Create a body mass index calculator app. It should take in height
#    in feet or meters and weight in lbs or kilograms and return the
#    associated body mass index. Post both the python code for your streamlit
#    app and a gif screen capture of it running.

import streamlit as st

def calculate_bmi(height, weight, height_unit, weight_unit):
    if height_unit == "feet":
        height = height * 0.3048  # Convert feet to meters
    if weight_unit == "lbs":
        weight = weight * 0.453592  # Convert lbs to kilograms

    bmi = weight / (height ** 2)
    return bmi

st.title("Body Mass Index (BMI) Calculator")

st.write("Please enter your height and weight:")

height = st.number_input("Height", min_value=0.0)
height_unit = st.selectbox("Height Unit", ["meters", "feet"])
weight = st.number_input("Weight", min_value=0.0)
weight_unit = st.selectbox("Weight Unit", ["kilograms", "lbs"])

if st.button("Calculate BMI"):
    bmi = calculate_bmi(height, weight, height_unit, weight_unit)
    st.write(f"Your BMI is: {bmi:.2f}")

    if bmi < 18.5:
      st.write("You are underweight.")
    elif 18.5 <= bmi < 25:
      st.write("You are normal weight.")
    elif 25 <= bmi < 30:
      st.write("You are overweight.")
    else:
      st.write("You are obese.")
