# -*- coding: utf-8 -*-
"""locationmap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lcANfYv3EwdUePiS6Dz39NIX2XteKFF-
"""

import streamlit as st
import folium

# Set the title of the app
st.title("Location Map")

# Add input fields in the sidebar
with st.sidebar:
    st.write("Enter coordinates:")
    lat = st.number_input("Latitude", min_value=-90.0, max_value=90.0, value=0.0)
    lon = st.number_input("Longitude", min_value=-180.0, max_value=180.0, value=0.0)

# Create a Folium map centered at the user-specified coordinates
m = folium.Map(location=[lat, lon], zoom_start=10)

# Add a marker at the specified location with a popup
folium.Marker([lat, lon], popup="Your location").add_to(m)

# Display the map in the Streamlit app using HTML component
st.components.v1.html(m._repr_html_(), width=700, height=500)

pip install streamlit

pip install folium